name: push package

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      publish: # for dry-run if set to false
        default: true
        description: Publish packages to Artifactory
        required: true
        type: boolean

jobs:
  push:
    environment: publish
    runs-on: ubuntu-22.04
    # Required for Option 2 (npmjs.com with Trusted Publishing)
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x # depends on the project

      # Option 1: Setup for Artifactory (private repos)
      - name: Setup .npmrc
        uses: devolutions/actions/npmrc-setup@v1
        with:
          npm_token: ${{ secrets.ARTIFACTORY_NPM_TOKEN }}

      # Option 2: For npmjs.com (public repos) using Trusted Publishing (OIDC)
      # No explicit setup step needed - npm uses OIDC automatically when id-token: write is present
      # Note: First publish must be done manually by DevOps to configure the trusted publisher
      # Documentation: https://docs.npmjs.com/trusted-publishers

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # this step could vary depending on the project
      - name: Build
        run: |
          npm ci
          npm run build

      # Option 1: Publish to Artifactory (private repos)
      - name: Push
        if: ${{ github.event.inputs.publish != 'false' }}
        run: |
          npm run publish:jfrog

      # Option 2: Publish to npmjs.com (public repos)
      - name: Push
        if: ${{ github.event.inputs.publish != 'false' }}
        run: npm publish

      # this step could vary depending on the project
      - uses: actions/upload-artifact@v4.3.6
        with:
          name: package
          path: dist/*

      # Option 2 only: Update Artifactory cache after npmjs.com publish
      - name: Update Artifactory Cache
        run: gh workflow run update-artifactory-cache.yml --repo Devolutions/scheduled-tasks --field package_name="<package-name>"
        env:
          GH_TOKEN: ${{ secrets.DEVOLUTIONSBOT_WRITE_TOKEN }}
