name: push package

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      publish: # for dry-run if set to false
        default: true
        description: Publish packages to Artifactory
        required: true
        type: boolean

jobs:
  push:
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # depends on the project

      - name: Setup .npmrc
        uses: devolutions/actions/npmrc-setup@v1
        with:
          npm_token: ${{ secrets.ARTIFACTORY_NPM_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: | # this step could vary depending on the project
          npm ci
          npm run build

      - name: Push
        if : ${{ github.event.inputs.publish != 'false' }}
        run: |  # this step could vary depending on the project
          npm run publish:jfrog

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/*
