name: push package

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      publish: # for dry-run if set to false
        default: true
        description: Publish packages to Artifactory
        required: true
        type: boolean

jobs:
  push:
    environment: publish
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x # depends on the project

      # If push to Artifactory
      - name: Setup .npmrc
        uses: devolutions/actions/npmrc-setup@v1
        with:
          npm_token: ${{ secrets.ARTIFACTORY_NPM_TOKEN }}

      # If push to NPMJS
      - name: Setup .npmrc
        run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # this step could vary depending on the project
      - name: Build
        run: |
          npm ci
          npm run build

      # this step could vary depending on the project
      - name: Push
        if : ${{ github.event.inputs.publish != 'false' }}
        run: |
          npm run publish:jfrog

      # this step could vary depending on the project
      - uses: actions/upload-artifact@v4.3.6
        with:
          name: package
          path: dist/*

      # If push to NPMJS
      - name: Update Artifactory Cache
        run: gh workflow run update-artifactory-cache.yml --repo Devolutions/scheduled-tasks --field package_name="slauth"
        env:
          GH_TOKEN: ${{ secrets.DEVOLUTIONSBOT_WRITE_TOKEN }}
